email: fake@gmail.com
password: pwd

disableAntiLock: False

remote: True

experienceLevel:
 internship: False
 entry: True
 associate: True
 mid-senior level: True
 director: True
 executive: True
 
jobTypes:
 full-time: True
 contract: True
 part-time: False
 temporary: False
 internship: False
 other: False
 volunteer: False
 
date:
 all time: True
 month: False
 week: False
 24 hours: False
 
positions:
 - QA Engineer
 - Quality Assurance  Engineer
#  - Software Test Engineer
#  - Test Automation Engineer
#  - Software Engineer in Test
locations:
- United States
# - Las Vegas Metropolitan Area
# - Austin, Texas Metropolitan Area
# - Dallas-Fort Worth Metroplex
# - Greater Anchorage Area
# - New York City Metropolitan Area
# - San Francisco Bay Area
# - Los Angeles Metropolitan Area
# - Honolulu Metropolitan Area
# - Greater Chicago Area
# - San Diego Metropolitan Area
# - Greater Seattle Area
# - Denver Metropolitan Area
# - Salt Lake City Metropolitan Area
# - Greater Minneapolis-St. Paul Area
# - Greater St. Louis
# - Greater Phoenix Area
# - Albuquerque-Santa Fe Metropolitan Area
# - Greater Houston
# - Oklahoma City Metropolitan Area
# - Kansas City Metropolitan Area
# - Greater New Orleans Region
# - Nashville Metropolitan Area
# - Greater Indianapolis
# - Columbus, Ohio Metropolitan Area
# - Detroit Metropolitan Area
# - Greater Pittsburgh Region
# - Greater Pittsburgh Region
# - Miami-Fort Lauderdale Area
# - Greater Tampa Bay Area
# - Greater Orlando
# - Jacksonville, Florida, United States
# - Greater Philadelphia
# - Greater Hartford
# - Greater Boston
distance: 100

outputFileDirectory: ./

companyBlacklist:
 #- company
 #- company2

titleBlacklist:
 #- word1
 #- word2

uploads:
 resume: ./resume.pdf
 # Cover letter is optional
 #coverLetter: C:\Users\myDirectory\CoverLettter.pdf


# ------------ QA section -------------------

# ------------ Additional parameters: checkboxes ---------------
checkboxes:
 # Do you have a valid driver's license? (yes/no checkbox)
 driversLicence: True
 # Will you now, or in the future, require sponsorship for employment visa status (e.g. H-1B visa status)? (yes/no checkbox)
 # This is relative to the location and your citizenship applying above, and same with legallyAuthorized.
 requireVisa: False
 # Are you legally authorized to work in COUNTRY? (yes/no checkbox)
 legallyAuthorized: True
 # We must fill this position urgently. Can you start immediately? (yes/no checkbox)
 urgentFill: True
 # Are you comfortable commuting to this job's location? (yes/no checkbox)
 commute: True
 # Have you completed the following level of education: DEGREE TYPE? (yes/no checkbox)
 degreeCompleted:
  - High School Diploma
  - Bachelor's Degree
  # - Associate's Degree
  # - Master's Degree
  # - Master of Business Administration
  # - Doctor of Philosophy
  # - Doctor of Medicine
  # - Doctor of Law
 # Are you willing to undergo a background check, in accordance with local law/regulations?
 backgroundCheck: True

# ------------ Additional parameters: univeristyGpa ---------------
universityGpa: 4.0

# ------------ Additional parameters: languages ---------------
languages:
 english: Professional # None, Conversational, Professional, Native or bilingual


# ------------ Additional parameters: years of INDUSTRY experience ---------------
# How many years of TECHNOLOGY experience do you currently have? (whole numbers only)
industry:
 # normal ones
 Accounting/Auditing: 0
 Administrative : 0
 Advertising : 0
 Analyst : 0
 Art/Creative: 0
 Business Development: 0
 Consulting: 0
 Customer Service: 0
 Distribution Design: 0
 Education: 0
 Engineering: 6
 Finance: 0
 General Business: 0
 Health Care Provider: 0
 Human Resources: 0
 Information Technology: 6
 Legal: 0
 Management: 0
 Manufacturing: 0
 Marketing: 0
 Public Relations: 0
 Purchasing: 0
 Product Management: 0
 Project Management: 0
 Production: 0
 Quality Assurance: 6
 Research: 0
 Sales: 0
 Science: 0
 Strategy/Planning: 0
 Supply Chain: 0
 Training: 0
 Writing/Editing: 0
 # end normal ones
 # put your custom ones here
 #C++: 0
 #Python: 1
 # default to put for any skill that you did not list
 default: 6
 # end custom ones


# ------------ Additional parameters: years of technology experience ---------------
# How many years of work experience do you have using TECHNOLOGY? (whole numbers only)
technology:
 #python: 0
 #selenium: 0
 # default to put for any skill that you did not list
 default: 6
# ------------ Additional parameters: personal info ---------------
personalInfo:
 First Name: Viktoryia
 Last Name: Ivanova
 Phone Country Code: United States (+1) # See linkedin for your country code, must be exact
 Mobile Phone Number: 1234567890
 Street address: 123 street
 City: Las Vegas, Nevada # Include the state/province as well!
 State: Nevada
 Zip: 89138
 Linkedin: https://www.linkedin.com/in/viktoryiaivanova/
 Website: https://www.linkedin.com/in/viktoryiaivanova/ # github/website is interchangable here

# ------------ Additional parameters: USA employment crap ---------------
eeo:
 gender: None
 race: None
 vetran: None
 disability: None
 citizenship: None
